{"name": "test_get_pro_intent", "status": "broken", "statusDetails": {"message": "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 16: invalid continuation byte", "trace": "self = <test_get_intent.TestIntent object at 0x0000024118AFE630>\n\n    @pytest.mark.api_intention_test\n    @allure.feature(\"测试环境通用意图识别\")\n    def test_get_pro_intent(self):\n        # 意图测试\n        # GetRequests().get_request(\"http://192.168.1.79:8900/intention/v2/skin\", \"GET\", \"skin_intent\",\n        #                           \"intent\\\\dermatology\\\\target.txt\",\n        #                           \"intent\\\\dermatology\\\\dermatology_test_data_3995.csv\", [\"sentence\"], \"label\",\n        #                           \"dermatology_intention_test_result.xls\",\n        #                           \"dermatology_intention_target_test_result.xls\")\n        # GetRequests().get_request(\"http://192.168.1.74:8911/gynaecology_intention/v1\", \"GET\", \"pro_intent\",\n        #                           \"intent\\\\gynaecology\\\\线上target.txt\",\n        #                           \"intent\\\\gynaecology\\\\妇科-总测试数据-线上线下.csv\", [\"sentence\", \"False\", \"gynaecology\"],\n        #                           \"label\",\n        #                           \"gynaecology_intention_test_result.xls\",\n        #                           \"gynaecology_intention_target_test_result.xls\")\n        GetRequests().get_request(\"http://192.168.1.79:8905/intention/v2/infertility\", \"GET\", \"a_intent\",\n                                  \"intent\\\\infertility\\\\test_target.txt\",\n                                  \"intent\\\\infertility\\\\不孕不育测试数据.csv\", [\"sentence\"],\n                                  \"label\",\n                                  \"infertility_intention_test_result.xls\",\n>                                 \"infertility_intention_target_test_result.xls\")\n\napi\\test_get_intent.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\api\\get_requests.py:163: in get_request\n    test_data = ChangeDataType.csv_to_dict(rootPath + \"\\\\testdata\\\\apidata\\\\\" + test_data_file)\n..\\commonfunc\\change_data_type.py:85: in csv_to_dict\n    test_data = pandas.read_csv(file, encoding=\"utf-8\")\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:676: in parser_f\n    return _read(filepath_or_buffer, kwds)\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:448: in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:880: in __init__\n    self._make_engine(self.engine)\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:1114: in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:1891: in __init__\n    self._reader = parsers.TextReader(src, **kwds)\npandas\\_libs\\parsers.pyx:529: in pandas._libs.parsers.TextReader.__cinit__\n    ???\npandas\\_libs\\parsers.pyx:720: in pandas._libs.parsers.TextReader._get_header\n    ???\npandas\\_libs\\parsers.pyx:916: in pandas._libs.parsers.TextReader._tokenize_rows\n    ???\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n>   ???\nE   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 16: invalid continuation byte\n\npandas\\_libs\\parsers.pyx:2063: UnicodeDecodeError"}, "start": 1594259536473, "stop": 1594259536475, "uuid": "f7f95086-7f3a-4b1e-975c-6038d82e4f83", "historyId": "5577602bedd8563b8ebaf88513cfdf02", "testCaseId": "49fe48d551064aad013d744258a73f22", "fullName": "pytest.api.test_get_intent.TestIntent#test_get_pro_intent", "labels": [{"name": "feature", "value": "测试环境通用意图识别"}, {"name": "tag", "value": "api_intention_test"}, {"name": "parentSuite", "value": "pytest.api"}, {"name": "suite", "value": "test_get_intent"}, {"name": "subSuite", "value": "TestIntent"}, {"name": "host", "value": "WIN-OQ20V7UABJF"}, {"name": "thread", "value": "17440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest.api.test_get_intent"}]}